on:
  push:
    paths:
      - '**.tf'
      - 'marketplace/**'
      - '!packer/**'
name:                          Marketplace
jobs:
  test-terraform-code:
    name:                      Update Stack Listing
    runs-on:                   ubuntu-latest
    env:
      TF_VAR_compartment_ocid: ${{ secrets.TF_VAR_compartment_ocid }}
      TF_VAR_fingerprint:      ${{ secrets.TF_VAR_fingerprint }}
      TF_VAR_private_key:      ${{ secrets.TF_VAR_private_key }}
      TF_VAR_private_key_path: $GITHUB_WORKSPACE/oci.pem
      TF_VAR_tenancy_ocid:     ${{ secrets.TF_VAR_tenancy_ocid }}
      TF_VAR_user_ocid:        ${{ secrets.TF_VAR_user_ocid }}
      API_CREDS:               ${{ secrets.API_CREDS }}
      BUILD_SCRIPT:            build.sh
    steps:
    - name:                    Checkout
      uses:                    actions/checkout@master
    - name:                    Terraform Apply
      uses:                    "oci-quickstart/oci-quickstart/actions/terraform-apply@master"
    - name:                    Build ORM Zip 
      uses:                    "oci-quickstart/oci-quickstart/actions/build-orm-zip@master"
      if:                      success()
    - name:                    Update Listing
      uses:                    "oci-quickstart/oci-quickstart/actions/update-listing@master"
      if:                      success()
