on: 
  push:
    paths: 
    - 'images/driverless ai/**'
    branches:
      - 'multilisting_support'
name: OCI-Marketplace
jobs:
  test-terraform-code: 
    name: Update Marketplace Image Listing 
    runs-on: ubuntu-latest
    env:
      TF_VAR_compartment_ocid: ${{ secrets.TF_VAR_compartment_ocid }}
      TF_VAR_fingerprint: ${{ secrets.TF_VAR_fingerprint }}
      TF_VAR_private_key: ${{ secrets.TF_VAR_private_key }}
      TF_VAR_private_key_path: $GITHUB_WORKSPACE/oci.pem
      TF_VAR_tenancy_ocid: ${{ secrets.TF_VAR_tenancy_ocid }}
      TF_VAR_user_ocid: ${{ secrets.TF_VAR_user_ocid }}
      API_CREDS: ${{ secrets.API_CREDS }}
      LISTING_DIR: 'images/driverless ai'
    steps:
    - name: Checkout Quickstart Repo
      uses: actions/checkout@master
      with:
        ref:                   multilisting_support
    - name: Create Partner Marketplace-ready Image
      uses: "oci-quickstart/oci-quickstart/actions/create-image@master"
      with:
        base-image: 'ocid1.image.oc1.iad.aaaaaaaavxqdkuyamlnrdo3q7qa7q3tsd6vnyrxjy3nmdbpv7fs7um53zh5q'
    - name: Update Marketplace Listing
      uses: "oci-quickstart/oci-quickstart/actions/update-listing@master"
      
      
